//
// objs/mandelbrot_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_OBJS_MANDELBROT_ISPC_H
#define ISPC_OBJS_MANDELBROT_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void mandelbrot_ispc(float x0, float y0, float x1, float y1, int32_t width, int32_t height, int32_t maxIterations, int32_t * output);
    extern void mandelbrot_ispc_withtasks(float x0, float y0, float x1, float y1, int32_t width, int32_t height, int32_t maxIterations, int32_t * output);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_OBJS_MANDELBROT_ISPC_H
